defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: todo
  password: testtest
  database: todo
  host: localhost
  port: 5432

development:
  <<: *defaults
  host: localhost

test:
  <<: *defaults
  database: todo_test
  min_messages: error

